<?php

namespace Ens\JobeetBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
	public function getWithJobs()
	{
		$query = $this->getEntityManager()->createQuery(
				'SELECT c FROM EnsJobeetBundle:Category c LEFT JOIN c.jobs j WHERE j.expires_at > :date'
		)->setParameter('date', date('Y-m-d H:i:s', time()));
	
		return $query->getResult();
	}
	
	public function getActiveJobs($category_id = null, $max = null, $offset = null)
	{
		$qb = $this->createQueryBuilder('j')
		->where('j.expires_at > :date')
		->setParameter('date', date('Y-m-d H:i:s', time()))
		->orderBy('j.expires_at', 'DESC');
	
		if($max)
		{
			$qb->setMaxResults($max);
		}
	
		if($offset)
		{
			$qb->setFirstResult($offset);
		}
	
		if($category_id)
		{
			$qb->andWhere('j.category = :category_id')
			->setParameter('category_id', $category_id);
		}
	
		$query = $qb->getQuery();
	
		return $query->getResult();
	}	
}
