ens_job:
    pattern:  /
    defaults: { _controller: "EnsJobeetBundle:Job:index" }

ens_job_show:
    pattern:  /job/{company}/{location}/{id}/{position}
    defaults: { _controller: "EnsJobeetBundle:Job:show" }
    requirements:
        id:  \d+
        
ens_job_new:
    pattern:  /new
    defaults: { _controller: "EnsJobeetBundle:Job:new" }

ens_job_create:
    pattern:  /create
    defaults: { _controller: "EnsJobeetBundle:Job:create" }
    requirements: { _method: post }

ens_job_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "EnsJobeetBundle:Job:edit" }

ens_job_update:
    pattern:  /{id}/update
    defaults: { _controller: "EnsJobeetBundle:Job:update" }
    requirements: { _method: post }

ens_job_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "EnsJobeetBundle:Job:delete" }
    requirements: { _method: post }
