<?php

namespace Ens\JobeetBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class JobController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Ens\JobeetBundle\Controller\JobController();
        return $instance;
    }
}
